### ISSUE TITLE
configuration disappeared with 3.0.1 update

### ISSUE THREAD

**Issue by mschulze0** [grains36/Dynamic-Report-Push#1]
Hi,

all my configurations disappeared when upgrading to 3.0.1, except the first one. All of them actually still work, they just don't show up in the configuration dialog anymore.

**Comment by grains36** [comment]
Thank you for bringing this to my attention. I released a new version that is waiting for approval from the Ex Mod reviewers. I'll close this issue. Please let me know if you have any additional issues. My response time is a little faster with email. I'm just not on Github that often.
