### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by mschulze0** [grains36/Dynamic-Report-Push#3]
Hi,

when running the module on PHP 8.1 it crashes when I try to do the report push. Are you working on PHP 8 compatibility?

**Comment by grains36** [comment]
I was able to confirm that it works with PHP 8.0.27. Are you sure it is configured correctly? I'm happy to look at it with you. Shoot me an email at Gary.Rains@duke.edu and we can set up a meeting.

**Comment by grains36** [comment]
The module works with PHP 8
