### ISSUE TITLE
External Module not working

### ISSUE THREAD

**Issue by robinfitz26** [grains36/Dynamic-Report-Push#4]
Hi Gary - I am at DCRI. We have installed this module in REDCap 13.1.26. When I click on DRP 1 after configuration, I receive only a message saying: Current Number of Records in Project PID 31 is : 0

Both the source and target studies have existing records with the same variable name of sdov. The report I created in the source project is simple and only contains the record id and the sdov.

Also, I only have the module configured in the source project as shown 
![image](https://user-images.githubusercontent.com/117391753/234629293-7e2483ff-d14f-461e-8ee4-27d4ec525012.png)

Do I need to enter the same info in the module config for the target study?

Any feedback as to why this is not working would be appreciated. 

Thanks much,
Robin Fitzpatrick
DCRI

**Comment by grains36** [comment]
I'm glad we were able to figure out that this is not a problem with the module.

**Comment by robinfitz26** [comment]
Thanks again for your assistance, Gary.

Thanks,
Robin
